[iOS] 이미지를 페이징하는 뷰를 구현하였습니다.
codesquad-member-2020/airbnb-02 pull request #37
Opened 2020-05-24 07:09 UTC by ehgud0670

### 이미지를 페이징하는 뷰 구현
> Issue #5 을 구현하였습니다.

* scrollView의 하위 뷰로 stackView가 있고, pageControl은 계층이 scrollView와 같습니다. 
* scrollView의 FrameLayoutGuide의 width를 scrollView의 하위뷰의 width로 줘야하는데 빈 stackView의 width와 관계를 맺을수 없어서 결국 코드로 구현하였고 xib파일, xib관련 코드는 모두 삭제하였습니다. 
  * 인터페이스 빌더로도 scrollView의 FrameLayoutGuide의 width를 주지 않으면 되지만, 그러면 린트가 생겨 코드로 하였습니다. 
* `scrollViewDidEndDecelerating` 메소드를 이용하여 contentOffset.x에 값에 맞게 pageControl의 currentPage가 바뀌도록 하였습니다.
* 이 부분이 제일 중요한데 처음에 image_url의 개수대로 stackView나 pageControl을 설정하기 위해 ` configure(count: Int)`를 구현하였고, 이후 사진을 한개씩 다운로드하는 비동기적인 상황에서 사진을 순서대로 받기 위해 `insert(at index: Int, image: UIImage)`을 구현하였습니다. 

> 구현 이미지 

![봄날은_간다](https://user-images.githubusercontent.com/38216027/82747088-ef31d400-9dd0-11ea-93f8-814983898e6c.gif)

2020-05-24 16:49 UTC, seizze reviewed
👍

2020-05-24 16:49 UTC, seizze commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
설정 관련 코드가 기능 별로 잘 모여있는 것 같습니다.
```swift
private let scrollView: UIScrollView = {
    // configure scrollView
}()
```
이 3줄의 코드는 이렇게 변경하면 가독성이 더 높아질 것 같습니다.

2020-05-24 16:49 UTC, seizze commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
이 부분과 페이지 컨트롤도 마찬가지로 가독성이 높아질 것 같습니다.

2020-05-24 16:49 UTC, seizze commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        ).isActive = true
```swift
scrollView.contentLayoutGuide.widthAnchor
    .constraint(equalTo: stackView.widthAnchor)
    .isActive = true
```
이런 식으로 내려쓰는 건 어떨까요?

2020-05-24 16:49 UTC, seizze commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
외부에서 호출하는 메서드와 private 메서드끼리 모아 주시면 좋을 것 같습니다.
저는 생성자, internal 메서드, private 메서드 순서로 작성하는 편입니다.

2020-05-24 16:49 UTC, seizze commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
인자 레이블을 `modular(of:divideBy:)`, `quotient(of:divideBy:)`로 변경하는 건 어떨까요?

2020-05-24 23:57 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
네 좋은 방법인것 같습니다. 
근데 해보는 중인데 delegate 설정하려면 lazy var로 선언해야되서 좀 아쉬운데 어떻게 할까요??

2020-05-24 23:59 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
delegate 만 빼고 하도록 되는 부분들만 설정하도록 하겠습니다.

2020-05-25 00:05 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        stackView.translatesAutoresizingMaskIntoConstraints = false
네 반영하였습니다.

2020-05-25 00:09 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
그러면 `configure(count: Int)` 아래에 `insert(at index: Int, image: UIImage)` 메소드를 두고,
`configure(count: Int)`에서 호출하는 private 메서드들은 `insert(at index: Int, image: UIImage)` 아래에 두겠습니다.

2020-05-25 00:11 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
네네, 인터널 메서드를 생성자 아래에 두는거 좋은것 같아요 👍

2020-05-25 00:27 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
네 반영하였습니다. 👍

2020-05-25 00:27 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +    }
반영하였습니다.

2020-05-25 00:28 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        ).isActive = true
네 반영하였습니다.

2020-05-25 00:29 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Views/ImagePagingView.swift
> +        scrollView.translatesAutoresizingMaskIntoConstraints = false
반영하였습니다.

2020-05-25 02:37 UTC, seizze requested changes

2020-05-25 02:37 UTC, seizze commented on iOS/Airbnb/Airbnb/Controllers/SearchViewController.swift
> -        super.viewDidLoad()
이건 왜 삭제하신건가요?? 이 부분만 다시 쓰시면 머지할 수 있을 것 같아요

2020-05-25 02:38 UTC, ehgud0670 commented on iOS/Airbnb/Airbnb/Controllers/SearchViewController.swift
> -        super.viewDidLoad()
어 이거 왜 삭제했지 넵

2020-05-25 03:25 UTC, seizze approved these changes

2020-05-25 03:25 UTC, merged